# Generated by Django 4.0 on 2023-06-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CottonRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, null=True)),
                ('cotton_type', models.IntegerField(null=True)),
                ('uom', models.CharField(max_length=50, null=True)),
                ('qty', models.IntegerField(null=True)),
                ('request_date', models.DateField(null=True)),
                ('request_time', models.CharField(max_length=20, null=True)),
                ('request_status', models.CharField(max_length=40, null=True)),
                ('message', models.CharField(max_length=500, null=True)),
                ('cotton_photo', models.FileField(null=True, upload_to='DOCUMENT/')),
            ],
        ),
        migrations.CreateModel(
            name='CottonSeparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_qty', models.IntegerField()),
                ('cleaned_cotton', models.IntegerField()),
                ('uncleaned_cotton', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FarmerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('cotton_type', models.IntegerField()),
                ('total_qty', models.CharField(max_length=50)),
                ('unit_price', models.IntegerField()),
                ('total', models.IntegerField()),
                ('payment_status', models.CharField(max_length=20)),
                ('payment_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cotton_level', models.CharField(max_length=50)),
                ('uom', models.IntegerField()),
                ('price', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.IntegerField()),
                ('utype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=10)),
                ('profile_photo', models.FileField(upload_to='DOCUMENT/')),
            ],
        ),
    ]
