# Generated by Django 5.2.1 on 2025-06-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotton_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddDealers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=50)),
                ("lname", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=50)),
                ("pincode", models.IntegerField()),
                ("email", models.CharField(max_length=50)),
                ("mobile_no", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="OtpCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp", models.IntegerField(null=True)),
                ("status", models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="cottonrequest",
            name="message",
        ),
        migrations.RemoveField(
            model_name="cottonseparation",
            name="cleaned_cotton",
        ),
        migrations.RemoveField(
            model_name="cottonseparation",
            name="uncleaned_cotton",
        ),
        migrations.AddField(
            model_name="cottonrequest",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cottonrequest",
            name="is_notified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cottonrequest",
            name="payment_status",
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="cottonrequest",
            name="received_status",
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="cottonseparation",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="cottonseparation",
            name="separation_type",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="cottonseparation",
            name="uom",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="cottonrequest",
            name="cotton_type",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="cottonseparation",
            name="total_qty",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="farmerpayment",
            name="cotton_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="marketprice",
            name="uom",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="userlogin",
            name="password",
            field=models.CharField(max_length=8),
        ),
    ]
