# Generated by Django 4.0 on 2023-06-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotton_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketprice',
            name='uom',
            field=models.CharField(max_length=50),
        ),
    ]
