# Generated by Django 4.0 on 2023-06-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotton_app', '0002_alter_marketprice_uom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottonrequest',
            name='cotton_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
