# Generated by Django 4.0 on 2023-07-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotton_app', '0005_alter_cottonrequest_id_alter_cottonseparation_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddDealers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='cottonseparation',
            name='cleaned_cotton',
        ),
        migrations.RemoveField(
            model_name='cottonseparation',
            name='uncleaned_cotton',
        ),
        migrations.AddField(
            model_name='cottonrequest',
            name='received_status',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='cottonseparation',
            name='separation_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cottonseparation',
            name='uom',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cottonseparation',
            name='total_qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='farmerpayment',
            name='cotton_type',
            field=models.CharField(max_length=50),
        ),
    ]
