# Generated by Django 4.0 on 2023-07-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotton_app', '0006_adddealers_remove_cottonseparation_cleaned_cotton_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottonrequest',
            name='payment_status',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
