# Generated by Django 4.0 on 2023-07-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotton_app', '0007_cottonrequest_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottonseparation',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
