# Generated by Django 4.0 on 2023-07-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotton_app', '0008_cottonseparation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
