# Generated by Django 4.0 on 2023-07-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotton_app', '0010_alter_userlogin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='password',
            field=models.IntegerField(max_length=8),
        ),
    ]
