# Generated by Django 5.2.1 on 2025-06-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotton_app", "0014_alter_adddealers_id_alter_cottonrequest_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cottonrequest",
            name="message",
        ),
        migrations.AddField(
            model_name="cottonrequest",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cottonrequest",
            name="is_notified",
            field=models.BooleanField(default=False),
        ),
    ]
