# Generated by Django 5.2.1 on 2025-06-25 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cotton_app", "0015_remove_cottonrequest_message_cottonrequest_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cottonrequest",
            name="is_notified",
        ),
    ]
