# Generated by Django 5.2.1 on 2025-06-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotton_app", "0016_remove_cottonrequest_is_notified"),
    ]

    operations = [
        migrations.AddField(
            model_name="cottonrequest",
            name="is_notified",
            field=models.BooleanField(default=False),
        ),
    ]
