# Generated by Django 5.2 on 2025-07-03 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotton_app', '0002_adddealers_otpcode_remove_cottonrequest_message_and_more'),
        ('cotton_app', '0017_cottonrequest_is_notified'),
    ]

    operations = [
    ]
